[abalone]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
sha256 = "sha256:17s4g2y2zzi3p9g90s61i0gmyaihqbvliwhlsl4w6l5arb6wsdyy"

[cancer]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wpbc.data"
sha256 = "sha256:13jw6jz5g8v175mbklygpzv0qhq7k4ql7h0d6wrahvq8nv6mrggj"

[cpu]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/cpu-performance/machine.data"
sha256 = "sha256:12s4pnfr2ydpk9hwrn6gkrihhappa15ryzma4i5a30c3zd90wpy9"

[ailerons]
url = "https://www.dcc.fc.up.pt/~ltorgo/Regression/ailerons.tgz"
sha256 = "sha256:1qcwxh5r8xvwh5r3y51kgn32fn83pzx4qvzrizbvf0d58rgvy0wj"

[compActs]
url = "https://www.dcc.fc.up.pt/~ltorgo/Regression/compact.tar.gz"
sha256 = "sha256:10bnnyq9bwpp8n9z3cmkx5n5cavhqj6ypr5dyaqwca6maw7x1z6q"

[elevators]
url = "https://www.dcc.fc.up.pt/~ltorgo/Regression/elevators.tgz"
sha256 = "sha256:15w8w05w9iwzj9mqhchjdmdydfzmmb921cmsx93h46ncdc92b40v"

[stock]
url = "https://www.dcc.fc.up.pt/~ltorgo/Regression/stock.tgz"
sha256 = "sha256:0mma9c6qd1js19nwf63syclr22j1krlmq050hvafqb9f0p95ak9p"

[triazines]
url = "https://www.dcc.fc.up.pt/~ltorgo/Regression/triazines.tar.gz"
sha256 = "sha256:0xkapr4p19ks429a8x704dmh1mgz6ajmzslgd1zlw9qzzz67g0rh"

[iris]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
sha256 = "sha256:1h2n4sg5cn54f4mqg9zd6kbsprl4pkcv89sdkcqicwiilxqqnq3g"

[wine]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
sha256 = "sha256:0nd6mvb7qgfjjr7j0n1rd02x8g3ji9xyaw1sal5xyl9x7whb3rkb"

[cancer_class]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
sha256 = "sha256:0jjzd71r9zzz4x9kss6a73zz1ai5ni9bda552yiyhnry3x0sy1nn"

[servo]
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/servo/servo.data"
sha256 = "sha256:03x098fhl6f9qw4macg6jgw76mkvba58fd698g82nvzqwx9g68kz"

[pumadyn-8fh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-8fh.tar.gz"
sha256 = "sha256:0dhd8r125kxff4x1n3d7f9niw56fn5hjwmd75k9bpn2j2pad7h1b"

[pumadyn-8fm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-8fm.tar.gz"
sha256 = "sha256:16vxp2zh679w573xicfh4qbrdkhfnznhl5d4hjah8gkgl94nclh4"

[pumadyn-8nh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-8nh.tar.gz"
sha256 = "sha256:17b6879xmdbgn39kfbyj4b5dzafxs5bwzf6s96x5rpr8i18rb0cc"

[pumadyn-8nm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-8nm.tar.gz"
sha256 = "sha256:09lvqabv8w9qhl6sdqfk8a1y3f0a6jcsn0p2krpx1ph654l6yrwq"

[pumadyn-32fh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-32fh.tar.gz"
sha256 = "sha256:1b7lmmlmd5lb4s3dpqhw3g6s7mafbgp7h4agv6x90gxgvjq3md12"

[pumadyn-32fm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-32fm.tar.gz"
sha256 = "sha256:0jnyamvy73v7i5654xxgwbrkikvm0j0zfzd9br7j5bx7qam2j7as"

[pumadyn-32nh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-32nh.tar.gz"
sha256 = "sha256:0bdwmgi7587dq43xnh8vn9fvc5cvpjcfw9r1crpyd01hipnfn69j"

[pumadyn-32nm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/pumadyn-family/pumadyn-32nm.tar.gz"
sha256 = "sha256:18jfinjsvzilqdlzv2cq714qlnv6w87w7iaiy7ggssiclfj86ykw"

[bank-8fm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-8fm.tar.gz"
sha256 = "sha256:1j78dawj0vhg1qvckm259d6gyhjgn4y3142wxqkkfjs6xfslja5n"

[bank-8fh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-8fh.tar.gz"
sha256 = "sha256:0jyqi8c4myc33i0cmm0bdi84009rj933p4wg3zm0b6yywb3kc9w7"

[bank-8nm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-8nm.tar.gz"
sha256 = "sha256:0pfy7bcj7zd7qqrz7amvxhjrv9f39zi11fbzszclbxjkqv53yv8y"

[bank-8nh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-8nh.tar.gz"
sha256 = "sha256:0fc162v7wk006sbbaa995hps3s28znsml4qhpqhism9qa36jcfhk"

[bank-32fm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-32fm.tar.gz"
sha256 = "sha256:04bnpflq6cwchhypc94ndjrcc6d0bzzac9wc7q1l5lmjzr5x4346"

[bank-32fh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-32fh.tar.gz"
sha256 = "sha256:1vs18n2dil657l9b74k0hadxm59fh83gb24p29vq6s8cm4rr468d"

[bank-32nm]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-32nm.tar.gz"
sha256 = "sha256:0bi605qa2jywm96p5c5missc0npq63qkzw06x26jjvagns8rllgb"

[bank-32nh]
url = "https://ftp.cs.toronto.edu/pub/neuron/delve/data/tarfiles/bank-family/bank-32nh.tar.gz"
sha256 = "sha256:1567ivhcnij02p2fb8vyzximp6ws3mk2hwxna0fcvw64py9hnrhz"
