
name: "nix CI"
on:
  push:
    branches:
      - master

jobs:
  run-devenv-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: tfm
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - name: devenv ci
      run: nix build -L .#ci
    - name: julia tests
      run: |
        export JULIA_PROJECT="$PWD"
        echo "::info ::JULIA_PROJECT=$JULIA_PROJECT"
        nix develop --impure --command julia --eval "using Pkg; Pkg.instantiate()"
        nix develop --impure --command julia --color=yes test/runtests.jl
