name: "Release"
on:
  push:
    tags:
      - '*'

jobs:
  build-default-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3.5.2
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: tfm
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix build -L
    - run: nix build -L .#libsvm-all -o libsvm
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          result/*
          libsvm/bin/*
          libsvm/lib/libsvm.3.so
          libsvm/include/svm.h
